repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        args:
          - --disable=duplicate-code
          - --good-names=df, r, c, db 
          - --disable=import-error
        language: python
        types:
          - python 
      - id: black
        name: black
        entry: poetry run black
        language: python
        types:
          - python 